version: "3"
services:
  clustersampleapp:
    image: cluster-sample-app:latest
    # image: xxx.registry.io/cluster-sample-app:latest
    ports:
      - 8080:3000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: awslogs
      options:
         awslogs-group: cluster-sample-app
         awslogs-region: eu-west-3
         awslogs-stream-prefix: cluster-sample-app